### ISSUE TITLE
What am i doing wrong ?

### ISSUE THREAD

**Issue by zerr0s** [adamreisnz/replace-in-file#13]
Hi, forgive me for my bad english.

I can't get your module working. What am i doing wrong ?
`const replace = require('replace-in-file');
const options = {
  files: [
    'package.json',
    'manage_app.sh',
  ],

  from: [/development/g, /dev/g],
  to: ['production', 'prod'],
  allowEmptyPaths: false,
  encoding: 'utf8',
};
replace(options)
   .then(changedFiles => {
      console.log('Modified files:', changedFiles.join(', '));
   })

  .catch(error => {
      console.error('Error occurred:', error);
  });`

`  const {files, from, to, allowEmptyPaths, encoding} = config;
        ^
 SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (xxx/node_modules/replace-in-file/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

Thanks.

**Comment by adamreisnz** [comment]
Hi @zerr0s, it looks like I accidentally used destructuring in the latest release (force of habit!) which isn't supported no Node < 6. So looks like you're probably using a lower version of Node.

I've rewritten this now in 2.3.2, can you try if that version works for you?

You will need at least Node 4 for this module to work.

**Comment by adamreisnz** [comment]
I'll close this issue now, if anything still comes up let me know @zerr0s
