### ISSUE TITLE
Using callbacks for `to` throws error

### ISSUE THREAD

**Issue by XmlmXmlmX** [adamreisnz/replace-in-file#130]
When I try the example from [here](https://github.com/adamreisnz/replace-in-file#using-callbacks-for-to), the following error will be thrown:

```batch
Error: Must specify string or regex to replace
    at parseConfig (.\node_modules\replace-in-file\lib\helpers\parse-config.js:41:11)
    at combineConfig (.\node_modules\replace-in-file\lib\helpers\combine-config.js:56:10)
    at main (.\node_modules\replace-in-file\bin\cli.js:29:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by adamreisnz** [comment]
That error gets thrown when `from` is undefined:

![image](https://user-images.githubusercontent.com/490562/106396836-5bd89480-646f-11eb-9d32-a28094f79463.png)

The `to` parameter is the one with the callback.

Can you show me your code that you used to generate this error?

**Comment by adamreisnz** [comment]
Since this is quite old I will go ahead and close this off, but feel free to reopen if you are still having issues.
