### ISSUE TITLE
Can't run the module of replace-in-file anymore 

### ISSUE THREAD

**Issue by idanSirin** [adamreisnz/replace-in-file#51]
Hi,
Since a few days it's not possible to run this module anymore.
The node console return an exception about unexpected token and doesn't compile it.
Please your assistance.

```
/Users/idan/repos/swapr-automation/node_modules/replace-in-file/lib/replace-in-file.js:30
  const {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/idan/repos/swapr-automation/node_modules/replace-in-file/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by adamreisnz** [comment]
The code it is erroring on is:

```
const {
    files, from, to, encoding, ignore, allowEmptyPaths, disableGlobs,
    dry, verbose,
  } = config;
```

This uses ES6 destructuring. If you are using an older version of Node (did you downgrade?) then this won't run. You need to use [at least Node version 6.4](https://node.green/#ES2015-syntax-destructuring--assignment) to support destructuring.
