### ISSUE TITLE
No files match the pattern

### ISSUE THREAD

**Issue by SouthRibbleTech** [adamreisnz/replace-in-file#82]
This is my config 

```
var options = {
    files: [
      `/etc/ansible/roles/customer_setups/${syndicate.subdomain}/customer_db_template/tasks/main.yml`,
      `/etc/ansible/roles/customer_setups/${syndicate.subdomain}/customer_app_template/tasks/main.yml`,
      `/etc/ansible/roles/customer_setups/${syndicate.subdomain}/customer_db_default_template/tasks/main.yml`,
      `/etc/ansible/roles/customer_setups/${syndicate.subdomain}/customer_proxy_config/files/site`,
    ],
    from: /placeholder_domain/g,
    to: syndicate.subdomain
  }
```

I get the following error
```
Error: No files match the pattern: /etc/ansible/roles/customer_setups/microlight/customer_db_template/tasks/main.yml
    at glob (/home/simon/sitebuilder/node_modules/replace-in-file/lib/helpers/glob-async.js:27:23)
    at f (/home/simon/sitebuilder/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/simon/sitebuilder/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:198:13)
    at Glob._finish (/home/simon/sitebuilder/node_modules/glob/glob.js:197:8)
    at done (/home/simon/sitebuilder/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/simon/sitebuilder/node_modules/glob/glob.js:688:12)
    at /home/simon/sitebuilder/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/simon/sitebuilder/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/simon/sitebuilder/node_modules/glob/glob.js:764:12)
    at RES (/home/simon/sitebuilder/node_modules/inflight/inflight.js:31:16)
    at f (/home/simon/sitebuilder/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:153:21)
```

Yet I can copy that path and type

```
nano /etc/ansible/roles/customer_setups/microlight/customer_db_template/tasks/main.yml
```

and the file opens

I have even tried setting permission on the folder & files to 777 and it still does not work.

**Comment by adamreisnz** [comment]
Hi there, that error is thrown by Glob, not replace-in-file, so I recommend either enquiring there or troubleshooting further with your glob pattern.

If needed, you can add glob configuration like so: https://github.com/adamreisnz/replace-in-file#specify-glob-configuration

**Comment by HershKirsh** [comment]
I had the same issue and adding glob configuration, like @adamreisnz recommended fixed it for me.
 I added `glob: {windowsPathsNoEscape: true}`
